name: Build

on:
  push:
    branches: [ '4.30' ]
  pull_request:
    branches: [ '4.30' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download nopCommerce source
      run: |
        wget https://github.com/nopSolutions/nopCommerce/releases/download/release-4.30/nopCommerce_4.30_Source.zip
        unzip nopCommerce_4.30_Source.zip -d $GITHUB_WORKSPACE
        rm nopCommerce_4.30_Source.zip
    - uses: actions/checkout@v2
      with:
        path: Plugins/Nop.Plugin.Misc.FreshAddressIntegration
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Add plugin and tests to nopCommerce source
      run: |
        dotnet sln NopCommerce.sln add Plugins/Nop.Plugin.Misc.FreshAddressIntegration/Source/Nop.Plugin.Misc.FreshAddressIntegration.csproj
        dotnet sln NopCommerce.sln add Plugins/Nop.Plugin.Misc.FreshAddressIntegration/Tests/Nop.Plugin.Misc.FreshAddressIntegration.Tests.csproj
    - name: Install SonarCloud scanner
      run: |
        mkdir -p ./.sonar/scanner
        dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner
    - name: Mark Projects to Skip for Sonar
      run: ./sonar-helper.sh
      working-directory: Plugins/Nop.Plugin.Misc.FreshAddressIntegration
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./.sonar/scanner/dotnet-sonarscanner begin /k:"dfar-io_freshaddress-integration-for-nopcommerce" /o:"dfar-io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**\Nop.Plugin.Misc.FreshAddressIntegration\Tests\coverage.opencover.xml"
        dotnet restore
        dotnet build --no-restore
        dotnet test Plugins/Nop.Plugin.Misc.FreshAddressIntegration/Tests/Nop.Plugin.Misc.FreshAddressIntegration.Tests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:Include="[Nop.Plugin.Misc.FreshAddressIntegration]*" /p:ExcludeByAttribute="ExcludeFromCodeCoverage" /p:CoverletOutputFormat=opencover
        ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
